---

- hosts: all

  vars:
    database_user: 'root'
    database_password: 'password'

  pre_tasks:
    - include: tasks/_base.yml

  roles:
    - git
    - oh-my-zsh
    - rvm
    - mariadb
    - php
    - mailcatcher
    - dnsmasq
    - wkhtmltopdf
    - nodejs
    - couchdb
    - elasticsearch
    - composer
