---

- hosts: all

  vars:
    database_user: 'root'
    database_password: 'password'

  tasks:
    - include: tasks/_base.yml

  roles:
    - git
    - oh-my-zsh
    - rvm
    - mariadb
    - php
    - mailcatcher
